### ISSUE TITLE
Installation - Please help

### ISSUE THREAD

**Issue by TonyFrend** [matthewturner/alexa-salus-it500#7]
Hi Matthew,

Have decided to try to install your Alexa app for the Salus IT500 but have encountered a bit of a road block..

Probably showing my ignorance in this area but here goes ....... 

I have installed the Alexa server (on my QNAP Linux NAS) which seemed to go as expected but I am now struggling to understand how to progress with installing your project. 

I have copied your installation steps below along with my questions.

**Check out this project** (Do I use the 'git install' command to do this?)

**Add this module to alexa-app-server** (How do I do this? - is there a link you could provide?)

**Launch server with your personal credentials as environment variables (eg USERNAME=xyz PASSWORD=abc)**  (Is there a command string I should use for this?_)

**Test on http://localhost:8080/alexa/boiler** (This I understand )

**Create a new skill in https://developer.amazon.com** (I have looked at the Amazon web site and how to do this is unclear)

**Declare your username/password and the default temperatures for on/off using environment variables** (Please add details of how I would do this)

Thank you for any help you can give me in this matter.

Best regards,

Tony

**Comment by matthewturner** [comment]
Hi Tony,

Sorry I haven't got any further with the Google Home integration.

I'll try and help with this, but it might help if you tell me what you are trying to achieve. Do you have an Alexa device?

The use of the alexa-server and the skill/lambda are mutually exclusive: if you set up the lambda/skill you won't need the local server.

If you do want to use a local server, these instructions were from the original implementer and while I got it working a long time ago, I haven't tried them since so it may take me a while to work it out.

Regards,
Matt

**Comment by TonyFrend** [comment]
Hi Matt,


Thank you for your prompt response. I now have an Alexa device (only one device to plug the gaps in my preferred Google Home platform).

I have a local QNAP NAS device (that runs a Linux OS) that I would like to use for the Alexa server. I have managed to install the alexa-app-server (using your link alexa-app-server ) onto this NAS that seemed to complete without error. 

I now need some advice on how to check out your project and add your module to the alexa-app-server. I have used git to install other git apps in the past (do I use this method for your module?).

Next, how do I launch the alexa-app-server? I assume that I use my Alexa credentials as the environmental variables.

Also, any advice on how I can create a new skill on the Amazon Alexa skills web site would be appreciated. I have looked at the Amazon web site and I have managed to create a skill for my Alexa account but cannot understand how to link this skill to my local Alexa server.

Finally, the last step of ‘Declare your username/password and the default temperatures for on/off using environment variables’. Please add some details of how I would do this.

Hope the above makes my confusion/lack of knowledge clearer.

Thank you again for any help you can give me in this matter.

Best regards,

Tony

**Comment by matthewturner** [comment]
The `alexa-app-server` is only really for testing as, in order to get an Alexa skill talking to it, you would have to open up ports on your firewall etc.

Given how cheap it is to run a lambda it might be better to jump straight to hosting your own skill which you can do [here](https://developer.amazon.com/alexa/console/ask?). I've already created the definition of the skill [here](https://github.com/matthewturner/alexa-salus-it500/blob/master/aws/skill.json) so you should be able to paste this definition into your new skill.

AWS have improved things somewhat so you can now configure the lambda directly from the skill. All the code you need is in this repo.
